### ISSUE TITLE
FTBFS 2024-08-15

### ISSUE THREAD

**Issue by xnox** [wolfi-dev/os#26401]
Generated with:

```
./cg build log --build-id=6a9cd064-7533-4046-ad92-44caa14b07b0 --search 'ERROR: failed to build package' --attrs pkg,arch | sort | cut -d\  -f2,14- | sed 's|^|- [ ] |'
```

```[tasklist]
### Tasks
- [x] 🔗 pkg=apache-arrow https://github.com/wolfi-dev/os/pull/26492
- [x] 🔗 pkg=cargo-auditable https://github.com/wolfi-dev/os/pull/26412
- [x] 🔗 pkg=clang-17
- [x] 🔗 pkg=clang-18
- [x] 🔗 pkg=collectd https://github.com/wolfi-dev/os/pull/26484
- [x] 🔗 pkg=composer
- [x] 🔗 pkg=delta
- [x] 🔗 pkg=freerdp
- [x] 🔗 pkg=gnupg https://github.com/wolfi-dev/os/pull/26406
- [x] 🔗 pkg=gtk-2.0
- [x] 🔗 pkg=helix
- [x] 🔗 pkg=hickory-dns
- [x] 🔗 pkg=ingress-nginx-controller-1.11
- [x] 🔗 pkg=ivykis
- [x] 🔗 pkg=jitsucom-bulker
- [x] 🔗 pkg=kube-fluentd-operator
- [x] 🔗 pkg=libcmis https://github.com/wolfi-dev/os/pull/30226
- [x] 🔗 pkg=libevdev https://github.com/wolfi-dev/os/pull/26423
- [x] 🔗 pkg=libffi https://github.com/wolfi-dev/os/pull/26422
- [x] 🔗 pkg=llvm-lld-18
- [x] 🔗 pkg=meilisearch
- [x] 🔗 pkg=neuvector-sigstore-interface
- [x] 🔗 pkg=nfs-utils
- [x] 🔗 pkg=njs
- [x] 🔗 pkg=nodejs-16
- [ ] 🔗 pkg=nodejs-19
- [x] 🔗 pkg=openjdk-10
- [x] 🔗 pkg=openjdk-12
- [x] 🔗 pkg=openjdk-7 https://github.com/wolfi-dev/os/pull/30228
- [x] 🔗 pkg=openjdk-8
- [x] 🔗 pkg=percona-server-8.3
- [x] 🔗 pkg=php-8.1
- [x] 🔗 pkg=pulseaudio
- [ ] 🔗 pkg=py3-ml-metadata
- [x] 🔗 pkg=py3-pycparser
- [x] 🔗 pkg=py3-pywinpty
- [x] 🔗 pkg=qt5-qtbase
- [x] 🔗 pkg=rabbitmq-server-3.13
- [x] 🔗 pkg=rancher-2.9
- [x] 🔗 pkg=riemann-c-client
- [x] 🔗 pkg=ruby3.2-aws-eventstream
- [x] 🔗 pkg=ruby3.2-aws-partitions
- [x] 🔗 pkg=ruby3.2-aws-sdk-cloudwatchlogs
- [x] 🔗 pkg=ruby3.2-aws-sdk-core
- [x] 🔗 pkg=ruby3.2-aws-sdk-kms
- [x] 🔗 pkg=ruby3.2-aws-sdk-s3
- [x] 🔗 pkg=ruby3.2-aws-sdk-sqs
- [x] 🔗 pkg=ruby3.2-aws-sigv4
- [x] 🔗 pkg=rust-1.29
- [ ] 🔗 pkg=sonar-scanner-cli-entrypoint
- [x] 🔗 pkg=suricata
- [x] 🔗 pkg=suricata-update
- [x] 🔗 pkg=trust-dns
- [x] 🔗 pkg=wasi-sdk
```

Individual build logs can be queried using ` ./cg build log --build-id=6a9cd064-7533-4046-ad92-44caa14b07b0 --package PKG --arch ARCH` using pr 19057

**Comment by justinvreeland** [comment]
sonar-scanner-cli-entrypoint and ruby3.2-aws-* are specifying branches that are regularly updated. Those projects also don't have tags that we can use for the versions we're on.  So the expected commits don't match and rebuilds will fail as soon as a new push happens. Since we don't keep src tar or source equivalents need to figure out how we want to deal with these. Maybe augment the git pipeline to use a specific commit instead of branch or tag.

**Comment by xnox** [comment]
> sonar-scanner-cli-entrypoint and ruby3.2-aws-* are specifying branches that are regularly updated. Those projects also don't have tags that we can use for the versions we're on. So the expected commits don't match and rebuilds will fail as soon as a new push happens. Since we don't keep src tar or source equivalents need to figure out how we want to deal with these. Maybe augment the git pipeline to use a specific commit instead of branch or tag.

@justinvreeland Note, it will get better soon once https://github.com/chainguard-dev/melange/pull/1516 makes it into wolfictl; as then periodic updatable things, with branch & expected-commit will reset to it; rather than fail the build.

**Comment by murraybd** [comment]
I did a test rebuild of the packages which were "unchecked" in the checklist on amd64 and queried the logs for arm64. I'm using the results of that to ✔ them off.

**Comment by murraybd** [comment]
I'm going to close out this over arching issue for individual issues about each package which fails to build.
