### ISSUE TITLE
[Wolfi Package Request]: neovim

### ISSUE THREAD

**Issue by joshrwolf** [wolfi-dev/os#5381]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Neovim!

### which versions of the software should we include?

stable and nightly

### Add some justification for why this specific package and versions are important.

some of us weird folks want to set up our dev env as a portable wolfi based container

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package
```[tasklist]
### Tasks
- [ ] lua5.1
- [ ] treesitter
- [ ] unibilium
- [ ] libtermkey
```
