### ISSUE TITLE
Fix Wolfi-bot broken PRs - Hacktoberfest 2023

### ISSUE THREAD

**Issue by erikaheidi** [wolfi-dev/os#7017]
The @wolfi-bot is a top contributor with its automated PRs, but it doesn't always get things right. This year for Hacktoberfest we invite the open source community to get involved with Wolfi by submitting PRs to fix broken Wolfi-bot contributions.

This is an umbrella issue that we'll use to keep track of Hacktoberfest contributions. 

### What we expect from contributions
- Choose an issue from the list. Make sure to leave a comment on the issue so that others know you are working on it.
- Create a new PR with your changes, so that we can tag it with the `hacktoberfest-accepted` label and make it a valid PR for Hacktoberfest.

Check also the [Wolfi contributing guide](https://github.com/wolfi-dev/os/blob/dfb8f4a553e894db861295be44ef5e4de3072022/CONTRIBUTING.md) for more information on how to get started.

```[tasklist]
### Tasks
- [ ] https://github.com/wolfi-dev/os/issues/7018
- [ ] https://github.com/wolfi-dev/os/issues/7019
- [ ] https://github.com/wolfi-dev/os/issues/7020
- [ ] https://github.com/wolfi-dev/os/issues/7022
- [ ] https://github.com/wolfi-dev/os/issues/7021
- [ ] https://github.com/wolfi-dev/os/issues/7023
- [ ] https://github.com/wolfi-dev/os/issues/7025
- [ ] https://github.com/wolfi-dev/os/issues/7026
- [ ] https://github.com/wolfi-dev/os/issues/7027
- [ ] https://github.com/wolfi-dev/os/issues/7028
- [ ] https://github.com/wolfi-dev/os/issues/7029
- [ ] https://github.com/wolfi-dev/os/issues/7033
- [ ] https://github.com/wolfi-dev/os/issues/7030
- [ ] https://github.com/wolfi-dev/os/issues/7031
- [ ] https://github.com/wolfi-dev/os/issues/7032
```
