### ISSUE TITLE
Ensure consistent config YAML formatting, including from tooling

### ISSUE THREAD

**Issue by luhring** [wolfi-dev/os#907]
## Context

Our goal for our package config files is that they can be manipulated **just as easily by humans as by automation**.

And we're seeing heavy usage from both types of actors. Wolfi contributions (from humans!) are ever-growing. And meanwhile, the team has invested in lots of tooling to help with the maintenance and scaling of the distro over time, primarily in [`melange`](https://github.com/chainguard-dev/melange/) and [`wolfictl`](https://github.com/wolfi-dev/wolfictl).

In order to facilitate smooth interoperability between manual and programmatic changes to our YAML files, it's essential that we always have a consistent approach to formatting this data.

Several months ago, I attempted to use [`yamlfmt`](https://github.com/google/yamlfmt) to format all configs ([link to PR](https://github.com/wolfi-dev/os/pull/372)). But this approach had two noticed weaknesses:

1. It provided no means of preserving readability aspects like empty lines between major sections.
2. It didn't integrate with our tooling code that interacted with YAML, so there was no guaranteed consistency between its formatting and our own code's effects on YAML.

After reflecting on what we wanted and where we had fallen short, I wrote https://github.com/chainguard-dev/yam, which solves both of the above weaknesses. Yam lets you configure gap lines based on data structure, and it exports a [formatted `Encoder`](https://github.com/chainguard-dev/yam/blob/main/pkg/yam/formatted/encoder.go#L23-L28) that can be plugged into other tooling that writes out YAML changes (e.g. to disk).

Yam, like the rest of our YAML-related functionality in `melange` and `wolfictl`, has a dependency on https://github.com/go-yaml/yaml, which has a small set of bugs we should resolve before we finalize our standardized formatting approach.

## The plan

```[tasklist]
### Tasks
- [ ] https://github.com/wolfi-dev/os/pull/894
- [x] yam: fix bug: mangling of comments in lists
- [x] yam: fix bug: removal of comments
- [x] yam: read configuration from file during encoding
- [x] yam: support linting/formatting all files in a directory at once
- [x] Use yam's `Encoder` in all `melange` YAML writes
- [x] Use yam's `Encoder` in all `wolfictl` YAML writes
- [ ] Format all config files in Wolfi with yam
- [ ] Enforce formatting in CI for Wolfi
```

**Comment by luhring** [comment]
After talking w/ @imjasonh, I decided to try to forego bug fixes in the upstream YAML library, in favor of intercepting its encoding process further directly in `yam`. I'll update the task list above accordingly.

**Comment by luhring** [comment]
Fixes are here: https://github.com/chainguard-dev/yam/pull/8

**Comment by luhring** [comment]
Multi-file/directory support: https://github.com/chainguard-dev/yam/pull/11

**Comment by luhring** [comment]
We'll wait on the remaining two task items until a scheduled "mass formatting" on Friday. This issue is blocked until then.
